pipeline {
    agent any
    environment {
        IMAGE = 'YOUR_ECR_OR_LOCAL_IMAGE'
    }
    stages {
        stage('Pull image') {
            steps {
                sh 'docker pull ${IMAGE}:latest || true'
            }
        }
        stage('Deploy to k8s') {
            steps {
                sh 'kubectl apply -f k8s/namespace.yaml'
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}